version: '3.8'

services:
  app:
    build:
      context: ./src
      dockerfile: DockerfileNode
    container_name: app
    ports:
      - "3001:3001"
    volumes:
      - ./src/uploads/users:/usr/src/app/uploads/users
      - ./src/uploads/movies/images:/usr/src/app/uploads/movies/images
      - ./src/uploads/movies/videos:/usr/src/app/uploads/movies/videos
    depends_on:
      - mongodb
      - cpp-server
    environment:
      - CONNECTION_STRING=mongodb://mongodb:27017/your-database
      - NODE_ENV=production
      - PORT=3001
      - CPP_SERVER_PORT=4000
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    logging:
        driver: "none"
  
  cpp-server:
    build:
      context: .
      dockerfile: ./src/cppCode/DockerfileProject 
    container_name: cpp-server
    ports:
      - "4000:4000"
    volumes:
      - ./data:/data
    command: ["4000"] 
    networks:
      - app-network

  frontend:
    build:
      context: ./netflix_og  
      dockerfile: DockerfileReact  
    container_name: react
    ports:
      - "3000:3000"  
    depends_on:
      - app
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
